typography_spectrum: 0.5339259828906506
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5885540016461164
  lightness: 0.6448425822891295
  saturation: 0.562671777792275
  rhythmicContrast: 0.07868238352239132
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.020937763852998614
analytics:
  google: UA-79726130-1
  facebook: null
  twitter: null
name: tips &amp; tricks
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: tricks & tips
purpose: []
